// Draw the C++-generated intensity values on the graph canvas.
function drawIntensityGraph(positions, intensities) {
    const canvas = document.getElementById("intensityGraph");
    const context = canvas.getContext("2d");

    const width = canvas.width;
    const height = canvas.height;
    const padding = 60;
    const sampleCount = positions.size();
    const minPosition = positions.get(0);
    const maxPosition = positions.get(sampleCount - 1);

    // Clear any graph left over from a previous draw.
    context.clearRect(0, 0, width, height);

    // Draw the vertical intensity axis and horizontal position axis.
    context.strokeStyle = "#888";
    context.lineWidth = 1;
    context.beginPath();
    context.moveTo(padding, padding);
    context.lineTo(padding, height - padding);
    context.lineTo(width - padding, height - padding);
    context.stroke();

    // Draw axis values and labels
    context.fillStyle = "#222";
    context.font = "14px sans-serif";

    // Horizontal position values, converted from meters to centimeters.
    context.textAlign = "center";
    context.fillText(
        `${(minPosition * 100).toFixed(1)} cm`,
        padding,
        height - padding + 22
    );
    context.fillText("0 cm", width / 2, height - padding + 22);
    context.fillText(
        `${(maxPosition * 100).toFixed(1)} cm`,
        width - padding,
        height - padding + 22
    );
    context.fillText(
        "Screen position",
        width / 2,
        height - 12
    );

    // Vertical intensity values.
    context.textAlign = "right";
    context.fillText("1.0", padding - 10, padding + 5);
    context.fillText("0.5", padding - 10, height / 2 + 5);
    context.fillText("0.0", padding - 10, height - padding + 5);

    // Rotated vertical-axis title.
    context.save();
    context.translate(18, height / 2);
    context.rotate(-Math.PI / 2);
    context.textAlign = "center";
    context.fillText("Normalized intensity", 0, 0);
    context.restore();

    // Draw the normalized intensity curve.
    context.strokeStyle = "#2563eb";
    context.lineWidth = 2;
    context.beginPath();

    for (let index = 0; index < sampleCount; index++) {
        const position = positions.get(index);
        const intensity = intensities.get(index);

        // Map the physical screen position across the drawable canvas width.
        const x =
            padding +
            ((position - minPosition) / (maxPosition - minPosition)) *
                (width - 2 * padding);

        // Canvas y-coordinates grow downward, so invert the intensity.
        const y =
            height -
            padding -
            intensity * (height - 2 * padding);

        if (index === 0) {
            context.moveTo(x, y);
        } else {
            context.lineTo(x, y);
        }
    }

    context.stroke();
}

// Load the WebAssembly module generated by Emscripten.
createDoubleSlitModule().then((Module) => {
    // Construct the C++ engine through its Embind wrapper.
    const engine = new Module.DoubleSlitEngine();

    // Confirm that the engine loaded successfully.
    document.getElementById("status").textContent = engine.status();

    // Ask C++ for 501 samples spanning -1 cm to +1 cm.
    const data = engine.generatePattern(-0.01, 0.01, 501);
    const positions = data.positions;
    const intensities = data.intensities;

    // Draw the generated interference pattern.
    drawIntensityGraph(positions, intensities);

    // Log a few values so the C++ to JavaScript transfer remains easy to verify.
    const middleIndex = Math.floor(positions.size() / 2);
    console.log("Position count:", positions.size());
    console.log("Intensity count:", intensities.size());
    console.log("First position:", positions.get(0));
    console.log("Center position:", positions.get(middleIndex));
    console.log("Center intensity:", intensities.get(middleIndex));
    console.log(
        "Last position:",
        positions.get(positions.size() - 1)
    );

    // Release the C++ objects stored in WebAssembly memory.
    positions.delete();
    intensities.delete();
    engine.delete();
});


// Governing wave propagation ideas
// dsin(theta) = m * lambda