// Draw the barrier, slit openings, and viewing screen.
function drawWaveGeometry() {
    const canvas = document.getElementById("waveCanvas");
    const context = canvas.getContext("2d");

    const barrierX = 220;
    const screenX = 820;
    const centerY = canvas.height / 2;
    const slitSeparation = 90;
    const slitHeight = 28;

    // Controls the slits
    const upperSlitY = centerY - slitSeparation / 2;
    const lowerSlitY = centerY + slitSeparation / 2;

    // Clear the previous frame and configure the geometry lines.
    context.clearRect(0, 0, canvas.width, canvas.height);
    context.strokeStyle = "#222";
    context.lineWidth = 5;

    // Draw three barrier segments, leaving an opening at each slit.
    context.beginPath();

    context.moveTo(barrierX, 0);
    context.lineTo(barrierX, upperSlitY - slitHeight / 2);

    context.moveTo(barrierX, upperSlitY + slitHeight / 2);
    context.lineTo(barrierX, lowerSlitY - slitHeight / 2);

    context.moveTo(barrierX, lowerSlitY + slitHeight / 2);
    context.lineTo(barrierX, canvas.height);

    context.stroke();

    // Draw the viewing screen.
    context.beginPath();
    context.moveTo(screenX, 20);
    context.lineTo(screenX, canvas.height - 20);
    context.stroke();

    // Label the fixed parts of the experiment.
    context.fillStyle = "#222";
    context.font = "16px sans-serif";
    context.textAlign = "center";
    context.fillText("Double slits", barrierX, 18);
    context.fillText("Screen", screenX, 18);

    // Canvas drawing context, barrier and screen position, upper
    // and lower slit positions
    return {
        canvas,
        context,
        barrierX,
        screenX,
        upperSlitY,
        lowerSlitY
    };
}

// Draw the C++-generated intensity values on the graph canvas.
function drawIntensityGraph(positions, intensities) {
    const canvas = document.getElementById("intensityGraph");
    const context = canvas.getContext("2d");

    const width = canvas.width;
    const height = canvas.height;
    const padding = 60;
    const sampleCount = positions.size();
    const minPosition = positions.get(0);
    const maxPosition = positions.get(sampleCount - 1);

    // Clear any graph left over from a previous draw.
    context.clearRect(0, 0, width, height);

    // Draw the vertical intensity axis and horizontal position axis.
    context.strokeStyle = "#888";
    context.lineWidth = 1;
    context.beginPath();
    context.moveTo(padding, padding);
    context.lineTo(padding, height - padding);
    context.lineTo(width - padding, height - padding);
    context.stroke();

    // Draw axis values and labels
    context.fillStyle = "#222";
    context.font = "14px sans-serif";

    // Horizontal position values, converted from meters to centimeters.
    context.textAlign = "center";
    context.fillText(
        `${(minPosition * 100).toFixed(1)} cm`,
        padding,
        height - padding + 22
    );
    context.fillText("0 cm", width / 2, height - padding + 22);
    context.fillText(
        `${(maxPosition * 100).toFixed(1)} cm`,
        width - padding,
        height - padding + 22
    );
    context.fillText(
        "Screen position",
        width / 2,
        height - 12
    );

    // Vertical intensity values.
    context.textAlign = "right";
    context.fillText("1.0", padding - 10, padding + 5);
    context.fillText("0.5", padding - 10, height / 2 + 5);
    context.fillText("0.0", padding - 10, height - padding + 5);

    // Rotated vertical-axis title.
    context.save();
    context.translate(18, height / 2);
    context.rotate(-Math.PI / 2);
    context.textAlign = "center";
    context.fillText("Normalized intensity", 0, 0);
    context.restore();

    // Draw the normalized intensity curve.
    context.strokeStyle = "#2563eb";
    context.lineWidth = 2;
    context.beginPath();

    for (let index = 0; index < sampleCount; index++) {
        const position = positions.get(index);
        const intensity = intensities.get(index);

        // Map the physical screen position across the drawable canvas width.
        const x =
            padding +
            ((position - minPosition) / (maxPosition - minPosition)) *
                (width - 2 * padding);

        // Canvas y-coordinates grow downward, so invert the intensity.
        const y =
            height -
            padding -
            intensity * (height - 2 * padding);

        if (index === 0) {
            context.moveTo(x, y);
        } else {
            context.lineTo(x, y);
        }
    }

    context.stroke();
}

// Load the WebAssembly module generated by Emscripten.
createDoubleSlitModule().then((Module) => {
    // Construct the C++ engine through its Embind wrapper.
    const engine = new Module.DoubleSlitEngine();

    // Confirm that the engine loaded successfully.
    document.getElementById("status").textContent = engine.status();

    // Ask C++ for 501 samples spanning -1 cm to +1 cm.
    const data = engine.generatePattern(-0.01, 0.01, 501);
    const positions = data.positions;
    const intensities = data.intensities;

    // Start the wavefront animation and draw the interference pattern.
    requestAnimationFrame(animateWavefronts);
    drawIntensityGraph(positions, intensities);

    // Log a few values so the C++ to JavaScript transfer remains easy to verify.
    const middleIndex = Math.floor(positions.size() / 2);
    console.log("Position count:", positions.size());
    console.log("Intensity count:", intensities.size());
    console.log("First position:", positions.get(0));
    console.log("Center position:", positions.get(middleIndex));
    console.log("Center intensity:", intensities.get(middleIndex));
    console.log(
        "Last position:",
        positions.get(positions.size() - 1)
    );

    // Release the C++ objects stored in WebAssembly memory.
    positions.delete();
    intensities.delete();
    engine.delete();
});

// Draw wavefronts emitted from both slits once per second.
function drawWavefronts(scene, t) {
    const context = scene.context;

    // Canvas coordinates for the slit plane and screen.
    const x_slits = scene.barrierX;
    const x_screen = scene.screenX;
    const y_upper = scene.upperSlitY;
    const y_lower = scene.lowerSlitY;

    // L_visual is the slit-to-screen distance measured in canvas pixels.
    const L_visual = x_screen - x_slits;

    // Slowed visualization values, not the physical speed of light.
    const v_visual = 120;
    const T_emission = 1;

    const emittedWavefrontCount = Math.floor(t / T_emission);
    const halfCanvasHeight = scene.canvas.height / 2;
    const r_max = Math.hypot(L_visual, halfCanvasHeight);

    // Clip rings to the region between the slits and the screen.
    context.save();
    context.beginPath();
    context.rect(x_slits, 0, L_visual, scene.canvas.height);
    context.clip();

    context.strokeStyle = "#2563eb";
    context.lineWidth = 2;

    for (let n = 0; n <= emittedWavefrontCount; n++) {
        // t_n is the time when wavefront n was emitted.
        const t_n = n * T_emission;
        const t_minus_t_n = t - t_n;

        // Governing propagation equation: r_n(t) = v_visual(t - t_n).
        const r_n = v_visual * t_minus_t_n;

        if (r_n < 0 || r_n > r_max) {
            continue;
        }

        // Draw the wavefront emitted from the upper slit.
        context.beginPath();
        context.arc(
            x_slits,
            y_upper,
            r_n,
            -Math.PI / 2,
            Math.PI / 2
        );
        context.stroke();

        // Draw the wavefront emitted from the lower slit.
        context.beginPath();
        context.arc(
            x_slits,
            y_lower,
            r_n,
            -Math.PI / 2,
            Math.PI / 2
        );
        context.stroke();
    }

    context.restore();
}

let waveAnimationStart;

// Redraw the fixed geometry and moving wavefronts every browser frame.
function animateWavefronts(timestamp) {
    if (waveAnimationStart === undefined) {
        waveAnimationStart = timestamp;
    }

    const millisecondsPerSecond = 1000;
    const t =
        (timestamp - waveAnimationStart) / millisecondsPerSecond;

    const scene = drawWaveGeometry();
    drawWavefronts(scene, t);

    requestAnimationFrame(animateWavefronts);
}
